<?php

return [
    'call_for_action_contact_us' => 'Please use the contact form to leave us a message in case you have any queries.',
    'warning_too_many_requests' => 'The system has detected a large volume of requests from your IP. Kindly wait a while between data requests. Failure to abide by this policy may result in your IP being blocked.',
    'price_trends' => 'To begin, please pick a commodity you wish to check the price trends of. The system will prepare a graph of the price trends of the commodity over the last six months.',
    'arrival_trends' => 'To begin, please pick a commodity you wish to check the arrival trends of. The system will prepare a graph of the arrival trends of the commodity over the last six months.',
    'introduction_first_para' => 'Kalimati Fruits and Vegetables Markets is the pioneer organized terminal wholesale market in Nepal where retailers, institutional consumers and other bulk consumers procure their supplies. This market alone covers 60 to 70 percent of demand of Kathmandu valley. For giving an organized shape to the marketing of agricultural produce, especially, vegetables and fruits in Kathmandu valley, Kalimati Fruits and Vegetables Wholesale Market was set up by then the Department of Food and Agriculture Marketing Services under the Ministry of Agriculture in 1986.',
    'introduction_second_para' => 'The need to bring improvement in the state of Kalimati market was identified as a priority. Hence an agreement (NEP/89/CO1) was signed in 1989 between Government of Nepal (GON) and United Nation\'s Capital Development Fund (UNCDF) to construct and equip the market with physical infrastructures. The present facilities are the outcome of that agreement.',
    'introduction_third_para' => 'In 1995, government felt the need of an independent body for the efficient operation and management of the market. Keeping this in view, Kalimati Fruits and Vegetables Wholesale Market Development Board was formulated on 13 February 1995 under the Development Board Act 1957. Likewise, with a view to manage the operations of the market in on organized way and ensuring planned development of agriculture marketing, the Government of Nepal has formulated new organizational set up "Kalimati Fruits and Vegetables Market Development Board 2002" replacing the previous one.',
    'about_us_first_para' => 'In 1995, government felt the need of an independent body for the efficient operation and management of the market. Keeping this in view, Kalimati Fruits and Vegetables Wholesale Market Development Board was formulated on 13 February 1995 under the Development Board Act 1957.',
    'about_us_second_para' => 'Likewise, with a view to manage the operations of the market in on organized way and ensuring planned development of agriculture marketing, the Government of Nepal has formulated new organizational set up "Kalimati Fruits and Vegetables Market Development Board 2002" replacing the previous one.',
    'about_us_third_para' => 'In the current process of widespread globalization, we in Kalimati Fruits and Vegetable Market Development Board understand that meeting Nepal\'s market requirement is essential to the success of our organization. We can say that the years we experienced in the past are significant years and it is clearly seen that we have intensively delivery our best performance to focus on Kalimati\'s Market Development.',
    'about_us_fourth_para' => 'In addition, we in Kalimati Fruits and Vegetable Market Development Board will intensively endeavor in development, empowerment and, awareness for the purpose of empowering farmers to get to have a voice in this day and age.',
];
